version: "3.2"

services:
    database:
        image: amsterdam/postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: tourbuzz
            POSTGRES_PASSWORD: insecure

    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - database
        links:
            - database:database
        environment:
            SYMFONY__TOURBUZZ__DATABASE_HOST: "database"
            SYMFONY__TOURBUZZ__DATABASE_PORT: "5432"
            SYMFONY__TOURBUZZ__DATABASE_NAME: "tourbuzz"
            SYMFONY__TOURBUZZ__DATABASE_USER: "tourbuzz"
            SYMFONY__TOURBUZZ__DATABASE_PASSWORD: "insecure"
            SYMFONY__TOURBUZZ__MAILER_TRANSPORT: "smtp"
            SYMFONY__TOURBUZZ__MAILER_HOST: "localhost"
            SYMFONY__TOURBUZZ__MAILER_USER: ""
            SYMFONY__TOURBUZZ__MAILER_PASSWORD: ""
            SYMFONY__TOURBUZZ__MAILER_PORT: "25"
            SYMFONY__TOURBUZZ__MAILER_ENCRYPTION: "ssl" # null, ssl, tls
            SYMFONY__TOURBUZZ__SECRET: "insecure" # random
            SYMFONY__TOURBUZZ__MAIL_FROM: "service@website-domain"
            SYMFONY__TOURBUZZ__MAIL_CC: "service@website-domain"
            SYMFONY__TOURBUZZ__RETENTION_POLICY: "P14D"
            SYMFONY__TOURBUZZ__REQUEST_CONTEXT_HOST: "website-domain" # domain, scheme and base url for links in e-mails
            SYMFONY__TOURBUZZ__REQUEST_CONTEXT_SCHEME: "https"
            SYMFONY__TOURBUZZ__REQUEST_CONTEXT_BASE_URL: ""
            SYMFONY__TOURBUZZ__MESSAGEBIRD_ENABLE: "true"
            SYMFONY__TOURBUZZ__MESSAGEBIRD_API_KEY: "insecure"
            SYMFONY__TOURBUZZ__SMS_ORGINATOR: "service-name"
            SYMFONY__TOURBUZZ__PIWIK_SITE_ID: "null" # null for no piwik integration
            SYMFONY__TOURBUZZ__TRUSTED_PROXIES: "127.0.0.1/32,192.168.0.0/16,172.16.0.0/12"
            SYMFONY__TOURBUZZ__AUTO_LOGIN_FROM_EMAIL: "PT5M"
