version: '2'
services:
  web:
    image: nginx:latest
    build: 
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "80:80"
    links:
      - php
  php:
    image: php:7-fpm
    build: 
      context: .
      dockerfile: Dockerfile_php