version: "3.2"

services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tourbuzz
      POSTGRES_PASSWORD: insecure

  web:
    build: .
    ports:
      - "80:80"
    links:
      - database:database
    environment:
      TOURBUZZ__DATABASE_HOST: "database"
      TOURBUZZ__DATABASE_PORT: "5432"
      TOURBUZZ__DATABASE_NAME: "tourbuzz"
      TOURBUZZ__DATABASE_USER: "tourbuzz"
      TOURBUZZ__DATABASE_PASSWORD: "insecure"
      TOURBUZZ__MESSAGEBIRD_ENABLE: "true"
      TOURBUZZ__MESSAGEBIRD_API_KEY: "insecure"
      TOURBUZZ__TRANSLATE_API_KEY: "insecure"
      TOURBUZZ__SENDGRID_API_KEY: "insecure"
